[package]
name = "Risp"
version = "0.1.0"
authors = ["Aidan Sojourner <aidan.sojourner@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "risp"
path = "src/main.rs"

[dependencies]
clap = "2.33.0"
